fix: --dry-run for SQLAlchemy clients with proper raw SQL
GoogleCloudPlatform/professional-services-data-validator pull request #1047
Opened 2023-11-15 21:07 UTC by nehanene15

Previously, the `--dry-run` flag, similar to the `--verbose` flag, didn't print the exact raw query w/client specific rendering for SQLAlchemy clients. This PR corrects that and adds tests for one non-SQLAlchemy backend (BigQuery) and one SQLAlchemy backend (MySQL).

This prevents rendering of `:param1` parameters and invalid quotes or backticks when printing a dry run.
This PR does not affect the current `-verbose` functionality since that flag should only be used for debugging purposes.

2023-11-15 21:07 UTC, nehanene15 commented
/gcbrun

2023-11-15 22:09 UTC, sundar-mudupalli-work requested changes
Looks Good Neha - would consider adding tests for other databases as well.

2023-11-15 22:09 UTC, sundar-mudupalli-work commented on tests/system/data_sources/test_bigquery.py
At line 1160, can you assert that "err" is "". If this test errors out, the error message will be printed, so we can find out the problem.

2023-11-15 22:09 UTC, sundar-mudupalli-work commented on tests/system/data_sources/test_mysql.py
Same comment as above regarding err.

Overall looks good - we also need to test for all the databases ? Of course the test will run long and it will be worth it if it catches any errors.

2023-11-16 14:44 UTC, nehanene15 commented on tests/system/data_sources/test_mysql.py
Good catch for handling the err - I'll add that. I think testing for all databases may be redundant - the goal of the tests here is to ensure the params/backtick syntax is properly rendered for SQLAlchemy clients + non-SQLAlchemy clients. We know the query itself is valid for all databases since our other tests assert successful validation.

Therefore, by testing on BQ (non Alchemy) and MySQL (Alchemy) I feel we cover both use cases.

2023-11-16 15:23 UTC, sundar-mudupalli-work approved these changes

2023-11-16 16:11 UTC, merged