docs: Add comments on both verbose and log-level parameters, also alter the…
GoogleCloudPlatform/professional-services-data-validator pull request #1257
Opened 2024-09-06 18:22 UTC by luispavaogoogle

… dry-run parameter as mandatory

closes #1161

2024-09-06 18:27 UTC, helensilva14 commented
/gcbrun

2024-09-09 23:44 UTC, sundar-mudupalli-work requested changes

2024-09-09 23:44 UTC, sundar-mudupalli-work commented on README.md
One small change - for dry run, the doc does not call out that it is optional, i.e. not enclosed within []
Otherwise looks Good - thank you for correcting the other typos an dworking on it Luis

2024-09-11 12:15 UTC, luispavaogoogle commented on README.md
Good morning @sundar-mudupalli-work ,I altered as you request, please check if it is ok. Thanks!

2024-09-11 18:01 UTC, sundar-mudupalli-work approved these changes
Thank you Luis. LGTM

2024-09-11 18:02 UTC, sundar-mudupalli-work commented
/gcbrun

2024-09-11 18:12 UTC, sundar-mudupalli-work commented
/gcbrun

2024-09-11 19:29 UTC, luispavaogoogle commented
/gcbrun

2024-09-11 20:20 UTC, merged