feat: add state manager client
GoogleCloudPlatform/professional-services-data-validator pull request #311
Opened 2021-09-23 16:11 UTC by dhercher

Adding a client to manage state (connections and configurations)

The client should transparently know which file system/source to use for the state.
Then have helper commands for any stateful operations we run, currently CRUD for connection management

2021-09-28 21:21 UTC, nehanene15 requested changes
Looks good, suggested two small changes + adding documentation about setting the 'PSO_DV_CONFIG_HOME' env var would be great

2021-09-28 21:21 UTC, nehanene15 commented on data_validation/__main__.py
> +    target_client = clients.get_data_client(mgr.get_connection_config(args.source_conn))
```suggestion
    target_client = clients.get_data_client(mgr.get_connection_config(args.target_conn))
```

2021-09-28 21:21 UTC, nehanene15 commented on tests/unit/test_state_manager.py
> +    assert connections == [TEST_CONN_NAME]
Could be useful to add tests here for invalid GCS/filesystem paths.

2021-09-30 15:58 UTC, nehanene15 approved these changes
LGTM

2021-09-30 17:21 UTC, merged

2021-11-13 13:22 UTC, bbrewington commented
@nehanene15 minor documentation issue, but was this formatting change intentional?

Below screenshot from commit: https://github.com/GoogleCloudPlatform/professional-services-data-validator/commit/e893ea5f723e0e33350410e64e0d588cc96b36cf

<img width="1240" alt="Screen Shot 2021-11-13 at 8 20 25 AM" src="https://user-images.githubusercontent.com/10573749/141645363-352bcda3-2818-4841-bbad-979f27443a18.png">

2021-11-15 17:56 UTC, nehanene15 commented
> @nehanene15 minor documentation issue, but was this formatting change intentional?

Thanks for catching this. I don't believe so; @dhercher correct me if I am wrong.