lets see what breaks
GoogleCloudPlatform/professional-services-data-validator pull request #469
Opened 2022-05-04 16:31 UTC by renzokuken

2022-05-04 16:32 UTC, renzokuken commented
/gcbrun

2022-05-29 08:33 UTC, dhercher requested changes

2022-05-29 08:33 UTC, dhercher commented on third_party/ibis/ibis_teradata/client.py
> +    def __init__(self, host, user_name, password, port=1025, logmech='TD2', use_no_lock_tables=False, convert_to_utc=True):
We could consider making this flag `default_time_zone="GMT"` and using that in the SQL below?  Then if someone actually uses a non-utc timezone they could specify that as well

2022-08-15 19:29 UTC, nehanene15 commented
@renzokuken Closing this out since we were unable to set a timezone via config variable. Instead, we suggest casting to a timestamp within a timezone ([reference](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/third_party/ibis/ibis_teradata/datatypes.py#L149
))

2022-08-15 19:29 UTC, closed without merging