feat: issue-496--Remove dependency on tables list for custom query va…
GoogleCloudPlatform/professional-services-data-validator pull request #537
Opened 2022-07-12 18:54 UTC by sramsrinivasan

…lidations

2022-07-12 18:54 UTC, sramsrinivasan commented
/gcbrun

2022-07-12 19:15 UTC, sramsrinivasan commented
/gcbrun

2022-07-12 20:23 UTC, sramsrinivasan commented
/gcbrun

2022-07-12 21:46 UTC, helensilva14 requested changes
LGTM! Since the dependency is being removed, the README can be updated on the sections about the custom query parameters:
- https://github.com/GoogleCloudPlatform/professional-services-data-validator#custom-query-column-validations
- https://github.com/GoogleCloudPlatform/professional-services-data-validator#custom-query-row-validations

2022-07-12 21:46 UTC, helensilva14 commented on docs/examples.md
> +data-validation validate custom-query --custom-query-type column  --source-query-file source_query.sql --target-query-file target_query.sql -sc my_bq_conn -tc my_bq_conn -tbls bigquery-public-data.ne
```suggestion
data-validation validate custom-query --custom-query-type column  --source-query-file source_query.sql --target-query-file target_query.sql -sc my_bq_conn -tc my_bq_conn
```

I think you missed to remove the tables list parameter here on the example

2022-07-12 21:46 UTC, helensilva14 commented on data_validation/__main__.py
> +    if args.tables_list is None and validate_cmd == "Custom-query":
```suggestion
    if args.tables_list is None and config_type == consts.CUSTOM_QUERY:
```
It'd be nice to reference the constant here and use the config type variable as it is used on the `config_type != consts.SCHEMA_VALIDATION`

2022-07-13 02:14 UTC, sramsrinivasan commented
/gcbrun

2022-07-13 16:15 UTC, nehanene15 requested changes
This change breaks row level custom query validations since it needs the schema/table name when building the config for row validation.

2022-07-13 16:15 UTC, nehanene15 commented on data_validation/__main__.py
> +    else:
There should be a cleaner way to condense this instead of the large conditional statement with very similar code in each block. The cli.get_tables_list() method should already return an empty list if `--tbls` is not provided (default_value = []).

2022-07-13 20:10 UTC, helensilva14 approved these changes

2022-07-13 20:50 UTC, closed without merging