feat: Oracle random row
GoogleCloudPlatform/professional-services-data-validator pull request #588
Opened 2022-09-16 21:04 UTC by nehanene15

Supports random row for Oracle.
Closes #584

2022-09-16 21:04 UTC, nehanene15 commented
/gcbrun

2022-09-16 21:32 UTC, dhercher requested changes
Consider adding some integration testing

2022-09-16 21:32 UTC, dhercher commented on data_validation/query_builder/random_row_builder.py
> +    from third_party.ibis.ibis_oracle.client import OracleClient
I would suggest using `clients.OracleClient` here even though you are using an import as an object in a less than natural way.

Might as well only have this whacky logic contained to one spot

2022-09-16 21:32 UTC, dhercher commented on data_validation/query_builder/random_row_builder.py
> +    from third_party.ibis.ibis_oracle.client import OracleClient
ditto for teradata

2022-09-19 18:30 UTC, nehanene15 commented
> Consider adding some integration testing

Yeah, I'm waiting on an Oracle instance we can use for testing to build out integration tests for Oracle row + random row. I'll create a new issue to build those out once an image is ready.

2022-09-21 16:25 UTC, dhercher approved these changes

2022-09-21 16:29 UTC, merged