fix: Row validation optimization to avoid select all columns
GoogleCloudPlatform/professional-services-data-validator pull request #599
Opened 2022-10-06 16:34 UTC by sramsrinivasan

2022-10-06 16:41 UTC, sramsrinivasan commented
/gcbrun

2022-10-06 16:44 UTC, sramsrinivasan commented
/gcbrun

2022-10-06 18:19 UTC, sramsrinivasan commented
/gcbrun

2022-10-06 18:53 UTC, sramsrinivasan commented
/gcbrun

2022-10-06 19:37 UTC, sramsrinivasan commented
/gcbrun

2022-10-06 21:00 UTC, sramsrinivasan commented
/gcbrun

2022-10-06 21:03 UTC, sramsrinivasan commented
/gcbrun

2022-10-06 21:55 UTC, sramsrinivasan commented
/gcbrun

2022-10-07 18:26 UTC, nehanene15 commented on data_validation/query_builder/query_builder.py
> +            calc_table = calc_table.projection(
Does there need to be an `if self.comparison_fields` conditional here? Or will row validations always have a comparison field populated here?

2022-10-10 15:24 UTC, nehanene15 commented on data_validation/query_builder/query_builder.py
> +            calc_table = calc_table.projection(
After testing, it seems it will always have a comparison_field

2022-10-10 15:53 UTC, nehanene15 requested changes

2022-10-10 15:53 UTC, nehanene15 commented on data_validation/query_builder/query_builder.py
> +        if validation_type == consts.ROW_VALIDATION:
I don't think we need to check for validation_type since comparison fields are only populated for row validation. We should keep the existing conditional for 'if self.comparison_fields' and make the QueryBuilder unaware of validation_type.

2022-10-10 16:37 UTC, nehanene15 commented on data_validation/query_builder/query_builder.py
> +        if validation_type == consts.ROW_VALIDATION:
Found that we need this if a user wants to use random rows or PKs in column validation

2022-10-10 16:37 UTC, sramsrinivasan commented on data_validation/query_builder/query_builder.py
> +        if validation_type == consts.ROW_VALIDATION:
here is one use case for which we need validation_type comparison. 
data-validation validate column -sc my_bq_conn -tc my_bq_conn -tbls bigquery-public-data.new_york_citibike.citibike_trips --grouped-columns usertype -sum num_bikes_available --primary-keys station_id -rr -rbs 10

below are the other use cases that gets corrected with this conditional check - 

FAILED tests/unit/test_data_validation.py::test_grouped_column_level_validation_perfect_match - ibis.common.exceptions.IbisTypeError: 'date_value' is not a field in ['id']
FAILED tests/unit/test_data_validation.py::test_calc_field_validation_calc_match - ibis.common.exceptions.IbisTypeError: 'date_value' is not a field in ['id']
FAILED tests/unit/test_data_validation.py::test_grouped_column_level_validation_non_matching - ibis.common.exceptions.IbisTypeError: 'date_value' is not a field in ['id']
FAILED tests/unit/test_data_validation.py::test_grouped_column_level_validation_smart_count - ibis.common.exceptions.IbisTypeError: 'date_value' is not a field in ['id']
FAILED tests/unit/test_data_validation.py::test_grouped_column_level_validation_multiple_aggregations - ibis.common.exceptions.IbisTypeError: 'date_value' is not a field in ['id']
FAILED tests/unit/test_data_validation.py::test_random_row_level_validation - ibis.common.exceptions.IbisTypeError: 'int_value' is not a field in ['id']

2022-10-10 16:37 UTC, nehanene15 approved these changes

2022-10-10 16:38 UTC, merged