fix: yaml validation files in gcs
GoogleCloudPlatform/professional-services-data-validator pull request #977
Opened 2023-09-08 05:06 UTC by sundar-mudupalli-work

This change fixes [972](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/972). When using `data-validation configs run -c gs://mudu-plex-pri-myb/db6rows/public.iowa_27rows/0001.yaml` was throwing an error.

This fix does not have a test cases. We don't have any GCS based test cases in unit tests. Do the unit tests have access to a GCS bucket ? I tested the fix manually and it works. It would be nice for this to be tested in the test suite

Sundar Mudupalli

2023-09-08 05:06 UTC, sundar-mudupalli-work commented
/gcbrun

2023-09-13 17:15 UTC, nehanene15 requested changes

2023-09-13 17:15 UTC, nehanene15 commented on data_validation/cli_tools.py
> +        if validation_name.startswith("gs://"):
I think this logic should go within the StateManager get_validation_config() function. In the function, we can check for `if validation_name.startswith("gs://")` similar to [this function](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/47154b4139bf22358359c53fe25bbce44745589f/data_validation/state_manager.py#L147).

2023-09-13 22:39 UTC, sundar-mudupalli-work commented
Neha,

Good question. I did a bit of research and understand the code better.

Summary: I think the fix I proposed is in the right place and happy to hear another point of view. Here is my reasoning:

1. The `class StateManager` is a _A utility to manage Data Validations long-lived configurations and state. The majority of this work is file system management of connections and validation files_.
2. The `StateManager` object upon instantiation decides whether it is working with the native filesystem or GCS. This value is in the object attribute `file_system` which is either `FileSystem.GCS` or `FileSystem.LOCAL`. If `StateManager` object is instantiated without any parameters, the `file_system` attribute is `FileSystem.LOCAL` unless the environment variable `PSO_DV_CONFIG_HOME` points to a GCS directory.
3. The specific error reported in [Issue 972](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/972) was `FileNotFoundError: [Errno 2] No such file or directory: './gs://mudu-plex-pri-myb/db6rows/public.iowa_27rows/0001.yaml'`. Issuing the same command with `PSO_DV_CONFIG_HOME` set to a GCS directory results in a slightly different error which is `ValueError: Invalid Cloud Storage Path: gs://mudu-plex-pri-myb/db6rows/validations/gs://mudu-plex-pri-myb/db6rows/public.iowa_27rows/0001.yaml`. This confirms the reasoning above.

If we want to read from a file in GCS, we must instantiate the `StateManager` object with the GCS prefix - which is what this code does.

We can instantiate a `StateManager` object with no parameters and then move this code to `get_validation_config`. The last line in `get_validation_config` is `_read_file` which depends on `file_system` attribute being set correctly. Because we instantiated `StateManager` with no parameters we will have to reset that attribute again in `get_validation_config`. Not a great idea in my opinion.

I looked at `list_validations_in_dir` function. The test `startswith("gs://")` appears unnecessary, it could have used the `self.file_system` attribute. This function is called from `__main__` and the `StateManager` is instantiated with the right parameter. This function is identical to the function `list_validations` right above it!!. These could have been collapsed into one function with `config_dir` as an optional argument with a default value of `None`.

Sorry about the long explanation - I am still learning this code base and hopefully you find it helpful.

Sundar Mudupalli

2023-09-18 19:37 UTC, nehanene15 commented on data_validation/cli_tools.py
> +            gcs_prefix = "/".join(validation_name.split("/")[: obj_depth - 1])
This might be easier than getting the depth - 1: `"/".join(file.split("/")[:-1])`

2023-09-18 19:37 UTC, nehanene15 commented
@sundar-mudupalli-work That makes sense. Seems like we need to clean up the StateManager functions a bit.
Left a small comment on optimizing the gcs_prefix path, but besides that LGTM

2023-09-28 15:44 UTC, nehanene15 approved these changes

2023-09-28 15:53 UTC, merged